### ISSUE TITLE
New Manifest details page

### ISSUE THREAD

**Issue by glenrobson** [glenrobson/SimpleAnnotationServer#104]
![sas-collection-ui-stage3-v03-canvases](https://user-images.githubusercontent.com/1969268/128358510-632afcfb-e2fb-4fb6-b664-b2fea202328a.png)

**Comment by glenrobson** [comment]
Allow switching between annotated canvases and canvases without annotations. 

Canvas: [1]

Keep in mind you may want show all canvases.

**Comment by glenrobson** [comment]
What does "export annotations" do on the top level?

**Comment by glenrobson** [comment]
I've replaced the trash bin with the content state link but what should it do at this level. Options include:
 * Content state link to canvas (note very few viewers can work with this at the moment)
 * Copy and paste link for the annotation list. This would be quite useful but could be next to the download annotations link

**Comment by glenrobson** [comment]
Changes

 *  Canvas: to Label: 
 * Default to all canvas showing but allow only annotated . 
 * Remove manifest link and replace with back to collection
 * Canvas content state call it Content State  
 * Add canvas titles fixed height box e..g Canvas / Annotated Canvas

**Comment by hxsllc** [comment]
Latest mockup aligning my design with your development and the comments above

![sas-collection-ui-stage3-v05-canvases](https://user-images.githubusercontent.com/29841283/129060895-96d37297-b50a-4421-8e09-8bbeae888cf1.png)

**Comment by hxsllc** [comment]
Note that I would choose "Export annotations (JSON)" rather than "Download". Download is more straightforward, but doesn't align/match up with Import. I think it's clearer to the user if they see both Import and Export options on the same page, so they understand they can Import the JSON file that they just exported (rather than downloaded).

The difference between "Remove" annotations and "Clear" annotations is minor. As long as it's not "Delete", it's good enough.

**Comment by glenrobson** [comment]
Ready for review.

**Comment by glenrobson** [comment]
Rename 
 * Manifest link to Content State link

**Comment by glenrobson** [comment]
I've removed the Content state link until we decide how the content state functionality should work. i.e.:

 * Is it a click through to a viewer?
 * Is it a copy of the content state?
