### ISSUE TITLE
Identifier not present in Search URI after registering a manifest

### ISSUE THREAD

**Issue by iz2axr** [glenrobson/SimpleAnnotationServer#39]
After registering a manifest in SAS, the identifier is not showing up in the search URI.  The generated URI is;

      http://localhost:8888/search-api//search

The manifest is available [here](https://api-pre.library.tamu.edu/fcrepo/rest/mwbManifests/CofeEarHis/Full_Manifest).

**Comment by glenrobson** [comment]
If you get the latest copy of SAS it should fix the issue of an empty identifier for the search.

The issue was I had a pretty fragile method of converting a manifest URI to a short identifier that worked with the manifest URIs I had tested but not for yours. It now produces a md5 string as an identifier which should be more robust. Please re-open if you find other issues.
